[package]
name = "mybridge-cxx"
authors = ["Raphael Menges"]
version = "0.0.0"
edition = "2024"
license = "MIT"

[lib]
name = "mybridgecxx"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
cxx = "1"

[build-dependencies]
cxx-build = "1"
