[package]
name = "rust-c"
authors = ["Raphael Menges"]
version = "0.0.0"
edition = "2024"
license = "MIT"

[lib]
name = "rustc"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
nalgebra = "0.34"
