name: Build

permissions:
  contents: "read"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - name: Setup Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build for macOS
        run: |
          cmake \
          -B build-macos \
          -S . \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_PREFIX_PATH="${QT_ROOT_DIR}" \
          -DCMAKE_TOOLCHAIN_FILE="${QT_ROOT_DIR}/lib/cmake/Qt6/qt.toolchain.cmake" \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0
          cmake --build build-macos
